import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AKIL
 */
public class postcomment extends javax.swing.JFrame {

    /**
     * Creates new form postcomment
     */
    public postcomment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JScrollPane jsp = new JScrollPane(jPanel1);
        add(jsp);
        int c=0;
        
        
        String   vname=NewJFramevideo.vname;
        String   uname=login.uname;
        try { 
            
            Class.forName("com.mysql.jdbc.Driver");
        		     System.out.println("jdbc:mysql://localhost/pcs");
        	             //"jdbc:mysql://" + ipaddress + "/" + databasename, login, pass
        		      Connection db = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pcs","root","akil");
        		    
        		      Statement st= (Statement) db.createStatement();
                             System.out.print("select * from uservideocomments where vname='"+vname+"' order by date limit 5");
                             ResultSet rs = st.executeQuery("select * from uservideocomments where vname='"+vname+"' order by  date limit 5 ");
                              while(rs.next()){
                            	  c++;
                            	  if(c==10)
                            		  break;
                            	  JLabel fff = new JLabel(rs.getString(2)+":");
                                 	jPanel1.add(fff);
                                 	   fff = new JLabel(rs.getString(3));
                                 	jPanel1.add(fff);
                                 	  fff = new JLabel("At "+rs.getString(4));
                                 	jPanel1.add(fff);
                      }    } catch (Exception e) {
                                
        		    	System.out.println("Could not initialize the database.");
        		      e.printStackTrace();
        		    }
        
        
      
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Comments");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Comment");
        
        
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               
            	
            	
            String reply=jTextArea1.getText();
          	String   vname=NewJFramevideo.vname;
            String   uname=login.uname;
                 if(Internetconection.isactive){
              try{   
             Class.forName("com.mysql.jdbc.Driver");
      		     System.out.println("jdbc:mysql://localhost/pcs");
      	             //"jdbc:mysql://" + ipaddress + "/" + databasename, login, pass
                         
      	Connection db = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pcs","root","akil");
      		     
      	Statement st= (Statement) db.createStatement();
        st.executeUpdate("insert into uservideocomments values('"+vname+"','"+uname+"','"+reply+"',now())");
            
                     //    System.out.print("insert into videocontent values('"+name+"','video/"+name+"','"+request.getParameter("desc")+"',0,0,0,0)");
          
              	}   catch (Exception e) {
      		     // out.print("Could not initialize the database.");
      		      e.printStackTrace();
      		    }
              JOptionPane.showMessageDialog(null, this, "Question Posted Successfully", 0);                    
                 }
                 else{
              	   
              	   jTextArea1.setText(jTextArea1.getText());
              	   jTextArea1.disable();
              	   System.out.println("connection is inactive");
              	 JOptionPane.showMessageDialog(null, this, "Cannot Post-connection Inactive,will be posted Soon", 0);                    
                 
                 }
            
                 
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(0, 3, 0, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	 LookAndFeel.main(null);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new postcomment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
