import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AKIL
 */
public class postaqsn extends javax.swing.JFrame {

    /**
     * Creates new form postaqsn
     */
    public postaqsn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter Your Question for the Discussion");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(qsn);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Post");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton1ActionPerformed(evt);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws InterruptedException {                                         
        // TODO add your handling code here:
    	postwhenonline();
    	      }                                        
static void postwhenonline() throws HeadlessException, InterruptedException{
	
	 qsn=jTextArea1.getText();
	   String   vname=NewJFramevideo.vname;
     String   uname=login.uname;
     if(InternetConnection.IsConnected()){
  try{   
 Class.forName("com.mysql.jdbc.Driver");
	     System.out.println("jdbc:mysql://localhost/pcs");
           //"jdbc:mysql://" + ipaddress + "/" + databasename, login, pass
             
Connection db = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pcs","root","akil");
	     
Statement st= (Statement) db.createStatement();
   st.executeUpdate("insert into discussion values('"+qsn+"','"+vname+"','"+uname+"',0,now())");
   
         //    System.out.print("insert into videocontent values('"+name+"','video/"+name+"','"+request.getParameter("desc")+"',0,0,0,0)");
   JOptionPane.showMessageDialog(new postaqsn(), "Question Posted Successfully");
  	}   catch (Exception e) {
	     // out.print("Could not initialize the database.");
	      e.printStackTrace();
	    }
        qsn="";
        
        
     }
     else{
  	   someqsn=false;
  	   qsn=  jTextArea1.getText();
  	   jTextArea1.setText(jTextArea1.getText());
  	   jTextArea1.disable();
  	   JOptionPane.showMessageDialog(new postaqsn(), "Connection is inactive,will be posted Soon");       	   
  	   System.out.println("connection is inactive");
  	   
  	   
  	   
     }


	
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       LookAndFeel.main(null);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new postaqsn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify     
    static String qsn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
    static boolean someqsn;

}
